apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-frontend
  namespace: inference-data-plane
spec:
  template:
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generation-worker
  namespace: inference-data-plane
spec:
  template:
    spec:
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
