apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../gke
  - vllm.yaml

images:
  - name: inference-data-plane/frontend
    newName: us-central1-docker.pkg.dev/anmho-infra-prod/inference/inference-frontend
    newTag: latest
  - name: inference-data-plane/inference-engine
    newName: us-central1-docker.pkg.dev/anmho-infra-prod/inference/inference-engine
    newTag: latest

patches:
  - path: configmap.yaml
  - path: data-plane-gpu-toleration.yaml
