services:
  inference-frontend:
    build:
      context: .
      dockerfile: crates/inference-frontend/Dockerfile
    environment:
      CONFIG_FILE: /app/config/service.yaml
      VALKEY_URL: redis://valkey:6379
    volumes:
      - ${CONFIG_FILE:-./config/local.yaml}:/app/config/service.yaml:ro
    ports:
      - "8080:8080"
    depends_on:
      - valkey
      - inference-engine

  inference-engine:
    build:
      context: .
      dockerfile: crates/inference-engine/Dockerfile
    environment:
      CONFIG_FILE: /app/config/service.yaml
      VALKEY_URL: redis://valkey:6379
      MODEL_ENDPOINT: http://host.docker.internal:18000
    volumes:
      - ${CONFIG_FILE:-./config/local.yaml}:/app/config/service.yaml:ro
    depends_on:
      - valkey

  valkey:
    image: valkey/valkey:9.1.0-alpine
    command: ["--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
