apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-frontend
  namespace: inference-data-plane
spec:
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-engine
  namespace: inference-data-plane
spec:
  template:
    spec:
      containers:
        - name: engine
          imagePullPolicy: Always
