apiVersion: crema/v1
kind: CremaConfig
spec:
  pollingInterval: 15
  scaledObjects:
    - spec:
        scaleTargetRef:
          name: projects/PROJECT_ID/locations/REGION/workerpools/inference-temporal-worker
        minReplicaCount: 0
        maxReplicaCount: 1
        triggers:
          - type: temporal
            metadata:
              endpoint: __TEMPORAL_ADDRESS__
              namespace: __TEMPORAL_NAMESPACE__
              taskQueue: inference-gpu
              targetQueueSize: "1"
              activationTargetQueueSize: "1"
              queueTypes: workflow,activity
              selectUnversioned: "true"
              __CREMA_TEMPORAL_API_KEY_FROM_ENV__
